### PR TITLE
WSL support.

### PR DESCRIPTION
**Pull request by itfranck**
Additional parameter to support WSL.

```
Register-SecretVault -ModuleName 'SecretManagement.LastPass' -VaultParameters @{wsl = $true }
```

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
I wonder if it would be better to do a vault parameter called `lpassPath` instead and then that way you can specify the path to `lpass` inside of wsl. I _thought_ that if you execute an executable that is in wsl that it will run _in_ wsl... but I could be wrong. It might be only the other way around (invoking windows exes in wsl)

**Comment by itfranck** [comment]
From [MS Docs - Windows interoperability with Linux](https://docs.microsoft.com/en-us/windows/wsl/interop#:~:text=c%2FProgram%20Files%22-,Run%20Windows%20tools%20from%20Linux,%2D%2D%20exceptions%20are%20explained%20below), I think what you describe is possible only from Linux to Windows and not the other way around. 

I don't think there is a way to do  something like /PathToLpassCli/lpass and call it from windows. Wouldn't you have to mount the vhdx first (I believe within wsl, you get the windows path mount but not the other way around)  ?

In the end, even if it is possible, I don't think it will change things much on the command execution speed but it will definitely make it harder to configure than just call wsl and will force you to unregister / register your vault again if you change distribution.

**Comment by TylerLeonhardt** [comment]
I guess wsl is pretty unique... it feels weird having a thing in our product just for wsl though... I'm going back and forth.

What about something like `@{ lpassCommand = "wsl lpass" }` and then the default will just be `lpass`? This would also support scenarios where folks don't add `lpass` to their `PATH` but have it somewhere else. They can just do: `@{ lpassCommand = "/path/to/lpass" }`.

2 birds, one bug fix? :)

**Comment by itfranck** [comment]
@TylerLeonhardt 
Done.

Indeed, this is a much better solution.

**Comment by TylerLeonhardt** [comment]
the only thing that is problematic here is spaces... `lpassCommand = "/tyler leonhardt/lpass"` that will break this... but I think the user needs to fix it from there perspective and do: `lpassCommand = "& '/tyler leonhardt/to/lpass'"` can you include this in the README? Other than that I think this can go in.

**Review by TylerLeonhardt — APPROVED** [review]
LGTM

**Comment by TylerLeonhardt** [comment]
@itfranck did you test if you can `Set-Secret`?

**Comment by itfranck** [comment]
@TylerLeonhardt 
There's indeed a problem. 

Not only with WSL but I assume if you try to set a secret, you'll get the same issue natively than I since 

```
$InputObject | Invoke-Expression -Command "$lpassCommand @Arguments"
```
is not good at all. 

I assume It would need to be  more like 

```
# For a path
Invoke-Expression -Command "$InputObject | $lpassCommand @Arguments"
```
but then it won't work for a command since you'd need to put the input in-between, something like : 
```
Invoke-Expression -Command "$lpassCommand  $InputObject | lpass @Arguments"
```

Without splitting the parameter name in two (to deal with the custom path and command separately), A proper working remediation could be to use the --Field=FIELD parameter (I assume we can put this parameter as many time as we have fields to edit.  

Give me 36h.
I'll make a PR to address this properly. 



Reference
https://lastpass.github.io/lastpass-cli/lpass.1.html

**Comment by TylerLeonhardt** [comment]
I think we'll have to special case wsl... Because for that, I think the command needs to be :

```pwsh
wsl $inputObject | lpass... 
```

But I could be wrong about that

**Comment by TylerLeonhardt** [comment]
In other news, I was writing some tests and found this behavior wasn't working so we shouldn't have this problem in the future :) I'll get those in once master is working.

**Pull request merged**
