### PR TITLE
Buffix/ignore errors elegantly

### PR DESCRIPTION
**Pull request by itfranck**
This seems to be an elegant solution to the problem and as far as I can tell, it work well. 

I tested
- While logged out : I received the expected error
- Setting a secret, I did not get any "Account not found" message when adding a new secret.

I can test the prompt window in 1h once I get disconnected.

### CODE REVIEW

**Comment by itfranck** [comment]
Prompt login window behavior work as expected.

**Comment by TylerLeonhardt** [comment]
Ok so since we are ignoring errors in checking if an account exists, I would think we would somehow trigger the login if it's needed before we do the ErrorAction Silently Continue call.

Does that make sense? Otherwise that call might hide the prompt

**Comment by itfranck** [comment]
@TylerLeonhardt 

I'd argued it was not necessarily needed.
My previous assumption that the error redirect discarded the login prompt was false (Brain glitch of mine ?)

Therefore, the `show` in `Set-Secret` did produce the prompt.
Cancelling the prompt through the cancel element will inevitably fail on the second `Set-Secret` call and produce the following error: 
```
'Error: Could not find decryption key. Perhaps you need to login with `lpass login`.'
```

That being said, I added additional validation after the initial call. 
I also removed the lpass cli messages from the function and put them in a constant.

**Comment by TylerLeonhardt** [comment]
I feel like if that's the case (prompt still shows up when error stream is redirected), then always redirecting errors to output is the right idea.

That said, I'm ok with what you have here and we can revisit that at a later time when more error text is leaking.

**Review by TylerLeonhardt — APPROVED** [review]

**Comment by TylerLeonhardt** [comment]
Today I will run the tests in my branch and if they work ill do a release

**Pull request merged**
